# Generated by Django 5.0.3 on 2024-04-03 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('job_type', models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('internship', 'Internship'), ('contract', 'Contract')], max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('benefits', models.TextField()),
                ('education', models.CharField(choices=[('high-school', 'High School'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD')], max_length=20)),
                ('skills', models.TextField()),
                ('application_email', models.EmailField(blank=True, max_length=254)),
                ('application_url', models.URLField(blank=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('pulled_at', models.DateTimeField(auto_now=True)),
                ('job_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobboard')),
            ],
        ),
    ]
