# Generated by Django 5.0.3 on 2024-04-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_job_company_website_job_experience_job_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='working_model',
            field=models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('on-site', 'On Site'), ('unspecified', 'Unspecified')], default='unspecified', max_length=25),
        ),
    ]
