# Generated by Django 5.0.3 on 2024-04-22 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_job_working_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobBoardSelector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_field', models.CharField(max_length=255)),
                ('css_selector', models.TextField()),
                ('job_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobboard')),
            ],
            options={
                'unique_together': {('job_board', 'job_field')},
            },
        ),
    ]
