# Generated by Django 5.0.3 on 2024-05-13 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_jobboardselector_job_board_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobboardsearchselector',
            unique_together={('job_board', 'selector_type')},
        ),
    ]
