# Generated by Django 5.0.3 on 2024-05-22 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_jobboardsearchselector_unique_together'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobboardsearchselector',
            name='selector_type',
            field=models.CharField(choices=[('search_title', 'Search Title Input'), ('search_location', 'Search Location Input'), ('search_submit', 'Search Submit Button'), ('next_page', 'Next Page Button'), ('result_iterator', 'Result Iterator')], max_length=100),
        ),
        migrations.CreateModel(
            name='SelectorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('error_message', models.TextField(blank=True, default='')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='app_selecto_content_477103_idx')],
            },
        ),
    ]
