# Generated by Django 5.0.3 on 2024-05-22 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_job_normalised_salary_alter_job_company_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('title', 'company', 'location', 'salary')},
        ),
    ]
