# Generated by Django 5.0.3 on 2024-06-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_job_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10)),
                ('quota', models.IntegerField(default=50)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('salary', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sector', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(default='#FFFFFF', max_length=7)),
                ('job_boards', models.ManyToManyField(related_name='job_profiles', to='app.jobboard')),
            ],
        ),
    ]
