# Generated by Django 5.0.3 on 2024-06-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_jobprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobprofile',
            old_name='color',
            new_name='colour',
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=20),
        ),
    ]
